default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default
  database: recruitment-web-app_development

test:
  <<: *default
  database: recruitment-web-app_test

production:
  <<: *default
  database: recruitment-web-app_production
  username: recruitment-web-app
  password: <%= ENV['RECRUITMENT-WEB-APP_DATABASE_PASSWORD'] %>
